"$schema" = "./node_modules/wrangler/config-schema.json"
name = "members-edit"
main = "./worker/index.ts"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat_v2"]
dev.port = 3000

[assets]
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[env.production.vars]
NODE_ENV = "production"
